### ISSUE TITLE
该工程怎么开发？

### ISSUE THREAD

**Issue by xwillmadeit** [0xLLLLH/react-krpano#1]
我想本地启动这个项目看看，没有在 package.json 中看到开发启动命令

**Comment by 0xLLLLH** [comment]
这个项目仅提供了组件，本身不是应用无法独立运行。
要本地尝试可以用CRA快速创建个新项目，然后按[README说明](https://github.com/0xLLLLH/react-krpano#-%E5%AE%89%E8%A3%85)引入krpano.js并添加npm包为新项目的依赖，从而在新项目中使用组件。

如果要本地调试代码或者贡献代码，则需要将本项目clone到本地，然后通过`npm link`将npm包链接到本地代码
