### ISSUE TITLE
Cannot read property 'index' of undefined

### ISSUE THREAD

**Issue by navalex** [0xLLLLH/react-krpano#2]
Hi,

I'm making an webapp using your package to use KRPano dynamically inside my reactjs app. It was working well, I'm using redux to manage data.
But at the moment where I connected the redux store to my API, it started to throw me this error in 2 situations:
1. When I fetch all Scenes info from the API. But if I hard copy the return of the API inside the redux store without fetching, it works well... (there is literally no difference in data structure)
2. When I change the currentScene value (through redux store too), but worked before I integrated all the API service

This error is thrown by KrpanoActionProxy.removeScene:54, Scene.tsx:98

Do you know what can cause this error ?

**Comment by 0xLLLLH** [comment]
I reproduced the error and need more time to debug it. I will update this thread if there's any progress.

**Comment by 0xLLLLH** [comment]
@navalex This issue seems to be caused by the `name`  of the scenes. All names should start with a letter.

**Comment by navalex** [comment]
Hmm okay that's seems to be a possibility, since I use my API the ID is fully managed by mongoose. You should maybe specify it in the doc, thank you !

**Comment by 0xLLLLH** [comment]
> Hmm okay that's seems to be a possibility, since I use my API the ID is fully managed by mongoose. You should maybe specify it in the doc, thank you !

To be honest, I didn't know about it before.
In the future, I will prefix names internally to avoid the crash caused by name.
