### ISSUE TITLE
[ERR_REQUIRE_ESM] require() of ES Module not supported

### ISSUE THREAD

**Issue by navalex** [0xLLLLH/react-krpano#6]
I'm trying to using the library on a NextJS project, but when I try to build it on production environment, it throw me this error:

`Error [ERR_REQUIRE_ESM]: require() of ES Module ./node_modules/@babel/runtime/helpers/esm/defineProperty.js from ./node_modules/@0xllllh/react-krpano/dist/cjs/index.js not supported.
Instead change the require of defineProperty.js in ./node_modules/@0xllllh/react-krpano/dist/cjs/index.js to a dynamic import() which is available in all CommonJS modules.`

I tried to clone the repo to make a workaround, but I'm not really an expert in TS and Rollup, i didn't founded a solution.
Probably update some packages or config ?

**Comment by 0xLLLLH** [comment]
I made a fix. Could you please try the latest version?

**Comment by navalex** [comment]
Seems to work just fine, thanks for your reactivity !
